name: project_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  url_launcher: ^6.0.9
  google_maps_flutter: ^2.2.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.0.4+1
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_native_splash:
  color: "#ffffff" # Set background color
  image: assets/images/burgan.png # Path to your Burgan Bank logo
  android: true
  ios: true
  web: true
  fullscreen: true # Make the splash screen fullscreen
  android_gravity: center # Position the logo at the center
  ios_content_mode: scaleAspectFit # Fit the logo nicely on iOS
  fade_in_duration: 1000 # Fade-in animation duration

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/burgan.jpg" # Path to Burgan Bank logo
